name: homestay_form
description: "A new Flutter project."
publish_to: 'none' # This keeps the project private
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.4.0 # Specify a version (latest known as of May 2025)

  # Other useful packages
  holiday_event_api: ^1.0.2
  url_launcher: ^6.1.7
  flutter_dotenv: ^5.0.2
  uuid: ^4.0.0
  pdf: ^3.6.0
  printing: ^5.7.0
  auto_size_text: ^3.0.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  change_app_package_name: ^1.4.0
  http: ^1.2.2
  table_calendar: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
