// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANkhHhC_a52hV7XSK2guBGteADQipzKfU',
    appId: '1:519117202524:web:edcb41d1eb161487ac7299',
    messagingSenderId: '519117202524',
    projectId: 'homestay-management-d133e',
    authDomain: 'homestay-management-d133e.firebaseapp.com',
    storageBucket: 'homestay-management-d133e.appspot.com',
    measurementId: 'G-DHNJQ3JX59',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkTVx3_BQJs_shtI_QACOZzU8nKEQzRYA',
    appId: '1:519117202524:ios:7eb58d2e289b3b25ac7299',
    messagingSenderId: '519117202524',
    projectId: 'homestay-management-d133e',
    storageBucket: 'homestay-management-d133e.appspot.com',
    iosBundleId: 'com.flutterdaily.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkTVx3_BQJs_shtI_QACOZzU8nKEQzRYA',
    appId: '1:519117202524:ios:a5330b054519d2edac7299',
    messagingSenderId: '519117202524',
    projectId: 'homestay-management-d133e',
    storageBucket: 'homestay-management-d133e.appspot.com',
    iosBundleId: 'com.aqwise.homestayForm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANkhHhC_a52hV7XSK2guBGteADQipzKfU',
    appId: '1:519117202524:web:a99e37b654aa4a2eac7299',
    messagingSenderId: '519117202524',
    projectId: 'homestay-management-d133e',
    authDomain: 'homestay-management-d133e.firebaseapp.com',
    storageBucket: 'homestay-management-d133e.appspot.com',
    measurementId: 'G-ZXYDD4K132',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSGAQJXVvdhe8lY-oWGobx1PyVDf0zpdE',
    appId: '1:519117202524:android:e5386e3bcd2444c6ac7299',
    messagingSenderId: '519117202524',
    projectId: 'homestay-management-d133e',
    storageBucket: 'homestay-management-d133e.appspot.com',
  );

}